<Project>
  <Import Project="../Directory.Build.props" />

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Bdgrz.Compliance.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
