<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Cntryl.Conventions.Testing.Analyzers" Version="1.0.0" />
    <PackageVersion Include="Cntryl.Conventions.Testing.CodeFixes" Version="1.0.0" />
    <PackageVersion Include="Cntryl.Portia.Abstractions" Version="0.2.0" />
    <PackageVersion Include="Cntryl.Portia.AspNetCore" Version="0.2.0" />
    <PackageVersion Include="Cntryl.Portia.Fitz" Version="0.2.0" />
    <PackageVersion Include="Cntryl.Portia.Testing" Version="0.2.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.12" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>
</Project>
