using System.Text.Json;
using System.Text.Json.Serialization;
using Cntryl.Portia;

namespace Bdgrz.Compliance;

[PortiaJsonContext]
[JsonSourceGenerationOptions(
    JsonSerializerDefaults.Web,
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower)]
[JsonSerializable(typeof(ContinueWithDeveloperIdentity))]
[JsonSerializable(typeof(ContinueWithOidcProvider))]
[JsonSerializable(typeof(AuthenticatedUserIdentity))]
[JsonSerializable(typeof(UserIdentityRegistered))]
[JsonSerializable(typeof(UserIdentityAuthenticated))]
[JsonSerializable(typeof(RegisterTenant))]
[JsonSerializable(typeof(TenantRegistration))]
[JsonSerializable(typeof(TenantRegistered))]
[JsonSerializable(typeof(RegisterTenantOwner))]
[JsonSerializable(typeof(TenantOwnerRegistered))]
[JsonSerializable(typeof(RegisterTenantSlug))]
[JsonSerializable(typeof(TenantSlugRegistered))]
[JsonSerializable(typeof(TenantSlugRegistrationRejected))]
[JsonSerializable(typeof(ConfirmTenantSlug))]
[JsonSerializable(typeof(RejectTenantSlug))]
[JsonSerializable(typeof(TenantSlugConfirmed))]
[JsonSerializable(typeof(TenantSlugRejected))]
[JsonSerializable(typeof(RequestTenantSlugSurrender))]
[JsonSerializable(typeof(TenantSlugSurrenderRequested))]
[JsonSerializable(typeof(SurrenderTenantSlug))]
[JsonSerializable(typeof(TenantSlugSurrendered))]
[JsonSerializable(typeof(TenantSlugSurrenderRejected))]
[JsonSerializable(typeof(ConfirmTenantSlugSurrender))]
[JsonSerializable(typeof(TenantSlugSurrenderConfirmed))]
[JsonSerializable(typeof(RejectTenantSlugSurrender))]
[JsonSerializable(typeof(TenantSlugSurrenderFailed))]
[JsonSerializable(typeof(MemberRegistered))]
[JsonSerializable(typeof(RegisterMember))]
[JsonSerializable(typeof(DefineTeam))]
[JsonSerializable(typeof(DefineRole))]
[JsonSerializable(typeof(AssignTeamMember))]
[JsonSerializable(typeof(AssignTeamRole))]
[JsonSerializable(typeof(AssignRolePermission))]
[JsonSerializable(typeof(TeamDefined))]
[JsonSerializable(typeof(TeamDeleted))]
[JsonSerializable(typeof(TeamMemberAssigned))]
[JsonSerializable(typeof(RoleDefined))]
[JsonSerializable(typeof(RoleDeleted))]
[JsonSerializable(typeof(RolePermissionAssigned))]
[JsonSerializable(typeof(TeamRoleAssigned))]
[JsonSerializable(typeof(PermissionProjectionState))]
[JsonSerializable(typeof(string))]
sealed partial class ComplianceCoreJsonContext : JsonSerializerContext;
