<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Cntryl.Portia.Fitz" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Compliance.Common/Compliance.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Bdgrz.Compliance.Tests" />
  </ItemGroup>
</Project>
